In [2]:
#import numpy
import numpy as np

In [3]:
#sample data used is 44 U.S president heights in centimeters in chronological order and stored them in a list, a built-in data type in python

heights = [189,170,189,163,183,171,185,168,173,183,173,173,175,178,183,193,178,173,174,183,183,180,170,178,182,180,183,178,182,175,179,183,193,182,183,177,185,188,188,188,185,191,158,135]

In [4]:
#simple code to know the numbers of presidents that are taller than 188cm, we could iterate through the list compare each element against 188, and increase the count by 1 as the criteria is met [ this is vanilla python -> not using the module numpy]

#assigning 0 to a variable
cnt = 0
#iterating through the list
for height in heights:
#setting a criteria comparing each element against 188 to see if the list is greater than 188. if True, increment the variable by 1
    if height > 188:
        cnt += 1
cnt
#output shows that there are 5 presidents that are taller than 188cm

5

In [5]:
#now using numpy to perform the same task
heights_arr = np.array(heights)
(heights_arr > 188).sum()

5

In [6]:
#Reshape

#other data we have collected includes the ages of the presidents
ages = [ 57,61,57,57,58, 57, 57, 61, 54, 68, 51, 49, 64, 50, 48, 65, 52, 56, 46, 54, 49, 51, 47, 55, 55, 54, 42, 51, 56, 55, 51, 54, 51, 60, 62, 43, 55, 56, 61, 52, 69, 64, 46, 54 ]

ages_arr = np.array(ages)

#since both heights and ages are all about the same presidents, we can combine them:
heights_and_ages = heights + ages
heights_and_ages_arr = np.array(heights_and_ages)
heights_and_ages_arr


array([189, 170, 189, 163, 183, 171, 185, 168, 173, 183, 173, 173, 175,
       178, 183, 193, 178, 173, 174, 183, 183, 180, 170, 178, 182, 180,
       183, 178, 182, 175, 179, 183, 193, 182, 183, 177, 185, 188, 188,
       188, 185, 191, 158, 135,  57,  61,  57,  57,  58,  57,  57,  61,
        54,  68,  51,  49,  64,  50,  48,  65,  52,  56,  46,  54,  49,
        51,  47,  55,  55,  54,  42,  51,  56,  55,  51,  54,  51,  60,
        62,  43,  55,  56,  61,  52,  69,  64,  46,  54])

In [8]:
#shape() and Reshape
#numpy arrays have an attribute called shape that returns a tuple with each index having the number of corresponding elements

heights_and_ages_arr.shape

#the reshape() function is used to change the shape of the numpy array without modifying the array data

#let us align height and age for each president and reorganize the data into 2 by 44 matrix where the first row contains all heights and the second row contains ages

heights_and_ages_arr = heights_and_ages_arr.reshape((2,44))
heights_and_ages_arr


#the reshaped array is now a 2darray, yet not that the original array is not changed. we can reshape an array in multiple ways, as long as the size of teh reshaped array matches that of the original array

array([[189, 170, 189, 163, 183, 171, 185, 168, 173, 183, 173, 173, 175,
        178, 183, 193, 178, 173, 174, 183, 183, 180, 170, 178, 182, 180,
        183, 178, 182, 175, 179, 183, 193, 182, 183, 177, 185, 188, 188,
        188, 185, 191, 158, 135],
       [ 57,  61,  57,  57,  58,  57,  57,  61,  54,  68,  51,  49,  64,
         50,  48,  65,  52,  56,  46,  54,  49,  51,  47,  55,  55,  54,
         42,  51,  56,  55,  51,  54,  51,  60,  62,  43,  55,  56,  61,
         52,  69,  64,  46,  54]])

In [64]:
#Data Type
#another characteristics about numpy array is that it is homogenous, meaning each element must be of the same data type

#for example, in heights_arr, we recorded all heights in whole numbers, thus ech element is stored as an integer in the array. to check the data type, use numpy.ndarray.dtype

heights_arr.dtype

dtype('int64')

In [65]:
#if we mixed a float number in, say, the first element is 189.0 instead of 189

heights_float = [189.0,170,189,163,183,171,185,168,173,183,173,173,175,178,183,193,178,173,174,183,183,180,170,178,182,180,183,178,182,175,179,183,193,182,183,177,185,188,188,188,185,191]

In [66]:
heights_float_arr = np.array(heights_float)
heights_float_arr
heights_float_arr.dtype

#if the first element is a float, all the other elements will be converted to floats. this shows the homogenous feature of numpy

dtype('float64')

In [67]:
#Assigning Single Values
#Sometimes you need to change the values of particular elements in the array. For example, we noticed the fourth entry in the heights_arr was incorrect, it should be 165 instead of 163, we can re-assign the correct number by:

heights_arr[3] = 165
heights_arr

array([189, 170, 189, 165, 183, 171, 185, 168, 173, 183, 173, 173, 175,
       178, 183, 193, 178, 173, 174, 183, 183, 180, 170, 178, 182, 180,
       183, 178, 182, 175, 179, 183, 193, 182, 183, 177, 185, 188, 188,
       188, 185, 191, 158, 135])

In [68]:
#in a 2darray, single values can be assigned easily, YOu can use indexing for one element, for example, change the fourth entry in heights_and_ages_arr to 165

heights_and_ages_arr[0,3] = 165
heights_and_ages_arr

array([[189, 170, 189, 165, 183, 171, 185, 168, 173, 183, 173, 173, 175,
        178, 183, 193, 178, 173, 174, 183, 183, 180, 170, 178, 182, 180,
        183, 178, 182, 175, 179, 183, 193, 182, 183, 177, 185, 188, 188,
        188, 185, 191, 158, 135],
       [ 57,  61,  57,  57,  58,  57,  57,  61,  54,  68,  51,  49,  64,
         50,  48,  65,  52,  56,  46,  54,  49,  51,  47,  55,  55,  54,
         42,  51,  56,  55,  51,  54,  51,  60,  62,  43,  55,  56,  61,
         52,  69,  64,  46,  54]])

In [69]:
# we can use slicing for multiple elements. for example, to replace the first row by its mean 180 in heights_and_ages_arr
heights_and_ages_arr[0,:] = 180
heights_and_ages_arr

#this replaces all the list of elements with a single digit 180

array([[180, 180, 180, 180, 180, 180, 180, 180, 180, 180, 180, 180, 180,
        180, 180, 180, 180, 180, 180, 180, 180, 180, 180, 180, 180, 180,
        180, 180, 180, 180, 180, 180, 180, 180, 180, 180, 180, 180, 180,
        180, 180, 180, 180, 180],
       [ 57,  61,  57,  57,  58,  57,  57,  61,  54,  68,  51,  49,  64,
         50,  48,  65,  52,  56,  46,  54,  49,  51,  47,  55,  55,  54,
         42,  51,  56,  55,  51,  54,  51,  60,  62,  43,  55,  56,  61,
         52,  69,  64,  46,  54]])

In [70]:
#we can also combine slicing to change any subset of the array. for example to reassign 0 to the left upper corner:

heights_and_ages_arr[:2,:2]
#this picks the first two elements of both lists

array([[180, 180],
       [ 57,  61]])

In [71]:
#Assigning an array to an array
#in addition, a 1darray or 2darry can be assigned to a subset of another 2darray, as long as their shapes match.

heights_and_ages_arr
#update the array back to its default values
heights_and_ages_arr[0,:] = heights_arr

heights_and_ages_arr[:,0] = [190,58]

In [97]:
#Combining two arrays
#oftentime we combine data stored in different arrays and we need to combine them into one to keep it in one place. For example, instead of having the ages stored in a list, it could be stored in a 2darray:

heights_arr = heights_arr.reshape((1,44))
ages_arr = ages_arr.reshape((1,44))

In [99]:
ages_arr

array([[57, 61, 57, 57, 58, 57, 57, 61, 54, 68, 51, 49, 64, 50, 48, 65,
        52, 56, 46, 54, 49, 51, 47, 55, 55, 54, 42, 51, 56, 55, 51, 54,
        51, 60, 62, 43, 55, 56, 61, 52, 69, 64, 46, 54]])

In [100]:
heights_arr

array([[189, 170, 189, 165, 183, 171, 185, 168, 173, 183, 173, 173, 175,
        178, 183, 193, 178, 173, 174, 183, 183, 180, 170, 178, 182, 180,
        183, 178, 182, 175, 179, 183, 193, 182, 183, 177, 185, 188, 188,
        188, 185, 191, 158, 135]])

In [101]:
height_age_arr = np.hstack((heights_arr, ages_arr))
height_age_arr

array([[189, 170, 189, 165, 183, 171, 185, 168, 173, 183, 173, 173, 175,
        178, 183, 193, 178, 173, 174, 183, 183, 180, 170, 178, 182, 180,
        183, 178, 182, 175, 179, 183, 193, 182, 183, 177, 185, 188, 188,
        188, 185, 191, 158, 135,  57,  61,  57,  57,  58,  57,  57,  61,
         54,  68,  51,  49,  64,  50,  48,  65,  52,  56,  46,  54,  49,
         51,  47,  55,  55,  54,  42,  51,  56,  55,  51,  54,  51,  60,
         62,  43,  55,  56,  61,  52,  69,  64,  46,  54]])

In [102]:
height_age_arr = np.vstack((heights_arr, ages_arr))
height_age_arr

array([[189, 170, 189, 165, 183, 171, 185, 168, 173, 183, 173, 173, 175,
        178, 183, 193, 178, 173, 174, 183, 183, 180, 170, 178, 182, 180,
        183, 178, 182, 175, 179, 183, 193, 182, 183, 177, 185, 188, 188,
        188, 185, 191, 158, 135],
       [ 57,  61,  57,  57,  58,  57,  57,  61,  54,  68,  51,  49,  64,
         50,  48,  65,  52,  56,  46,  54,  49,  51,  47,  55,  55,  54,
         42,  51,  56,  55,  51,  54,  51,  60,  62,  43,  55,  56,  61,
         52,  69,  64,  46,  54]])

In [103]:
#concatenate
#more generally, we can use the function numpy.concatenate. if we want to concatenate, link together, two arrays along rows, then pss 'axis = 1' to achieve the same result as using numpy.hstack; and pass 'axis=0' if you want to combine arrays vertically

#in the previous example, we were using hstack to combine two arrays horizontally, instead:

height_age_arr = np.concatenate((heights_arr, ages_arr), axis = 1)
height_age_arr

array([[189, 170, 189, 165, 183, 171, 185, 168, 173, 183, 173, 173, 175,
        178, 183, 193, 178, 173, 174, 183, 183, 180, 170, 178, 182, 180,
        183, 178, 182, 175, 179, 183, 193, 182, 183, 177, 185, 188, 188,
        188, 185, 191, 158, 135,  57,  61,  57,  57,  58,  57,  57,  61,
         54,  68,  51,  49,  64,  50,  48,  65,  52,  56,  46,  54,  49,
         51,  47,  55,  55,  54,  42,  51,  56,  55,  51,  54,  51,  60,
         62,  43,  55,  56,  61,  52,  69,  64,  46,  54]])

In [104]:
height_age_arr = np.concatenate((heights_arr, ages_arr), axis = 0)
height_age_arr

array([[189, 170, 189, 165, 183, 171, 185, 168, 173, 183, 173, 173, 175,
        178, 183, 193, 178, 173, 174, 183, 183, 180, 170, 178, 182, 180,
        183, 178, 182, 175, 179, 183, 193, 182, 183, 177, 185, 188, 188,
        188, 185, 191, 158, 135],
       [ 57,  61,  57,  57,  58,  57,  57,  61,  54,  68,  51,  49,  64,
         50,  48,  65,  52,  56,  46,  54,  49,  51,  47,  55,  55,  54,
         42,  51,  56,  55,  51,  54,  51,  60,  62,  43,  55,  56,  61,
         52,  69,  64,  46,  54]])

In [114]:
import numpy as np

n,p = [int(x) for x in input().split()]
lista = []
for i in range(n):
    lista.append(input().split())
print(np.array(lista)astype(np.float16).mean(axis = 1).round(2))

AttributeError: 'tuple' object has no attribute 'split'