In [1]:
import numpy as np

In [3]:
heights = [189,170,189,163,183,171,185,168,173,183,173,173,175,178,183,193,178,173,174,183,183,180,170,178,182,180,183,178,182,175,179,183,193,182,183,177,185,188,188,188,185,191]

In [4]:
cnt = 0
for height in heights:
    if height > 188:
        cnt += 1
print(cnt)

5


In [5]:
heights_arr = np.array(heights)
print((heights_arr > 188).sum())

5


In [6]:
ages = [ 57,61,57,57,58, 57, 57, 61, 54, 68, 51, 49, 64, 50, 48, 65, 52, 56, 46, 54, 49, 51, 47, 55, 55, 54, 42, 51, 56, 55, 51, 54, 51, 60, 62, 43, 55, 56, 61, 52, 69, 64, 46, 54, 47, 70]

In [8]:
heights_and_ages = heights + ages
print(heights_and_ages)

[189, 170, 189, 163, 183, 171, 185, 168, 173, 183, 173, 173, 175, 178, 183, 193, 178, 173, 174, 183, 183, 180, 170, 178, 182, 180, 183, 178, 182, 175, 179, 183, 193, 182, 183, 177, 185, 188, 188, 188, 185, 191, 57, 61, 57, 57, 58, 57, 57, 61, 54, 68, 51, 49, 64, 50, 48, 65, 52, 56, 46, 54, 49, 51, 47, 55, 55, 54, 42, 51, 56, 55, 51, 54, 51, 60, 62, 43, 55, 56, 61, 52, 69, 64, 46, 54, 47, 70]


In [9]:
heights_and_ages_arr = np.array(heights_and_ages)
heights_and_ages_arr.shape

(88,)

In [11]:
heights_and_ages_arr.reshape((2,44))

array([[189, 170, 189, 163, 183, 171, 185, 168, 173, 183, 173, 173, 175,
        178, 183, 193, 178, 173, 174, 183, 183, 180, 170, 178, 182, 180,
        183, 178, 182, 175, 179, 183, 193, 182, 183, 177, 185, 188, 188,
        188, 185, 191,  57,  61],
       [ 57,  57,  58,  57,  57,  61,  54,  68,  51,  49,  64,  50,  48,
         65,  52,  56,  46,  54,  49,  51,  47,  55,  55,  54,  42,  51,
         56,  55,  51,  54,  51,  60,  62,  43,  55,  56,  61,  52,  69,
         64,  46,  54,  47,  70]])

In [12]:
heights_arr[2]

189

In [14]:
heights_and_ages_arr[0,1]

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [15]:
heights_and_ages_arr

array([189, 170, 189, 163, 183, 171, 185, 168, 173, 183, 173, 173, 175,
       178, 183, 193, 178, 173, 174, 183, 183, 180, 170, 178, 182, 180,
       183, 178, 182, 175, 179, 183, 193, 182, 183, 177, 185, 188, 188,
       188, 185, 191,  57,  61,  57,  57,  58,  57,  57,  61,  54,  68,
        51,  49,  64,  50,  48,  65,  52,  56,  46,  54,  49,  51,  47,
        55,  55,  54,  42,  51,  56,  55,  51,  54,  51,  60,  62,  43,
        55,  56,  61,  52,  69,  64,  46,  54,  47,  70])

In [16]:
height_and_ages_arr = heights_and_ages_arr.reshape((2,44))

In [19]:
height_and_ages_arr[0,1]

170

In [18]:
height_and_ages_arr

array([[189, 170, 189, 163, 183, 171, 185, 168, 173, 183, 173, 173, 175,
        178, 183, 193, 178, 173, 174, 183, 183, 180, 170, 178, 182, 180,
        183, 178, 182, 175, 179, 183, 193, 182, 183, 177, 185, 188, 188,
        188, 185, 191,  57,  61],
       [ 57,  57,  58,  57,  57,  61,  54,  68,  51,  49,  64,  50,  48,
         65,  52,  56,  46,  54,  49,  51,  47,  55,  55,  54,  42,  51,
         56,  55,  51,  54,  51,  60,  62,  43,  55,  56,  61,  52,  69,
         64,  46,  54,  47,  70]])

In [20]:
#this extracts the 1st row and 1st to the 3rd column
height_and_ages_arr[0,0:3]

array([189, 170, 189])

In [21]:
#same with the one above
height_and_ages_arr[0,:3]

array([189, 170, 189])

In [27]:
height_and_ages_arr = heights_and_ages_arr.reshape((2,44))

In [29]:
heights_and_ages_arr

array([189, 170, 189, 163, 183, 171, 185, 168, 173, 183, 173, 173, 175,
       178, 183, 193, 178, 173, 174, 183, 183, 180, 170, 178, 182, 180,
       183, 178, 182, 175, 179, 183, 193, 182, 183, 177, 185, 188, 188,
       188, 185, 191,  57,  61,  57,  57,  58,  57,  57,  61,  54,  68,
        51,  49,  64,  50,  48,  65,  52,  56,  46,  54,  49,  51,  47,
        55,  55,  54,  42,  51,  56,  55,  51,  54,  51,  60,  62,  43,
        55,  56,  61,  52,  69,  64,  46,  54,  47,  70])

In [30]:
height_and_ages_arr

array([[189, 170, 189, 163, 183, 171, 185, 168, 173, 183, 173, 173, 175,
        178, 183, 193, 178, 173, 174, 183, 183, 180, 170, 178, 182, 180,
        183, 178, 182, 175, 179, 183, 193, 182, 183, 177, 185, 188, 188,
        188, 185, 191,  57,  61],
       [ 57,  57,  58,  57,  57,  61,  54,  68,  51,  49,  64,  50,  48,
         65,  52,  56,  46,  54,  49,  51,  47,  55,  55,  54,  42,  51,
         56,  55,  51,  54,  51,  60,  62,  43,  55,  56,  61,  52,  69,
         64,  46,  54,  47,  70]])

In [31]:
height_and_ages_arr[:,3]

array([163,  57])

In [32]:
heights_and_ages_arr[3]

163

In [40]:
height_and_ages_arr = heights_and_ages_arr.reshape((2,44))

In [41]:
heights_and_ages_arr

array([189, 170, 189, 163, 183, 171, 185, 168, 173, 183, 173, 173, 175,
       178, 183, 193, 178, 173, 174, 183, 183, 180, 170, 178, 182, 180,
       183, 178, 182, 175, 179, 183, 193, 182, 183, 177, 185, 188, 188,
       188, 185, 191,  57,  61,  57,  57,  58,  57,  57,  61,  54,  68,
        51,  49,  64,  50,  48,  65,  52,  56,  46,  54,  49,  51,  47,
        55,  55,  54,  42,  51,  56,  55,  51,  54,  51,  60,  62,  43,
        55,  56,  61,  52,  69,  64,  46,  54,  47,  70])

In [42]:
height_and_ages_arr

array([[189, 170, 189, 163, 183, 171, 185, 168, 173, 183, 173, 173, 175,
        178, 183, 193, 178, 173, 174, 183, 183, 180, 170, 178, 182, 180,
        183, 178, 182, 175, 179, 183, 193, 182, 183, 177, 185, 188, 188,
        188, 185, 191,  57,  61],
       [ 57,  57,  58,  57,  57,  61,  54,  68,  51,  49,  64,  50,  48,
         65,  52,  56,  46,  54,  49,  51,  47,  55,  55,  54,  42,  51,
         56,  55,  51,  54,  51,  60,  62,  43,  55,  56,  61,  52,  69,
         64,  46,  54,  47,  70]])

In [46]:
heights_and_ages_arr

array([189, 170, 189, 163, 183, 171, 185, 168, 173, 183, 173, 173, 175,
       178, 183, 193, 178, 173, 174, 183, 183, 180, 170, 178, 182, 180,
       183, 178, 182, 175, 179, 183, 193, 182, 183, 177, 185, 188, 188,
       188, 185, 191,  57,  61,  57,  57,  58,  57,  57,  61,  54,  68,
        51,  49,  64,  50,  48,  65,  52,  56,  46,  54,  49,  51,  47,
        55,  55,  54,  42,  51,  56,  55,  51,  54,  51,  60,  62,  43,
        55,  56,  61,  52,  69,  64,  46,  54,  47,  70])

In [39]:
heights_and_ages_arr

array([189, 170, 189, 163, 183, 171, 185, 168, 173, 183, 173, 173, 175,
       178, 183, 193, 178, 173, 174, 183, 183, 180, 170, 178, 182, 180,
       183, 178, 182, 175, 179, 183, 193, 182, 183, 177, 185, 188, 188,
       188, 185, 191,  57,  61,  57,  57,  58,  57,  57,  61,  54,  68,
        51,  49,  64,  50,  48,  65,  52,  56,  46,  54,  49,  51,  47,
        55,  55,  54,  42,  51,  56,  55,  51,  54,  51,  60,  62,  43,
        55,  56,  61,  52,  69,  64,  46,  54,  47,  70])

In [47]:
height_and_ages_arr = heights_and_ages_arr.reshape((2,44))

In [48]:
height

191

In [49]:
height_and_ages_arr

array([[189, 170, 189, 163, 183, 171, 185, 168, 173, 183, 173, 173, 175,
        178, 183, 193, 178, 173, 174, 183, 183, 180, 170, 178, 182, 180,
        183, 178, 182, 175, 179, 183, 193, 182, 183, 177, 185, 188, 188,
        188, 185, 191,  57,  61],
       [ 57,  57,  58,  57,  57,  61,  54,  68,  51,  49,  64,  50,  48,
         65,  52,  56,  46,  54,  49,  51,  47,  55,  55,  54,  42,  51,
         56,  55,  51,  54,  51,  60,  62,  43,  55,  56,  61,  52,  69,
         64,  46,  54,  47,  70]])

In [53]:
height_and_ages_arr

array([[189, 170, 189, 163, 183, 171, 185, 168, 173, 183, 173, 173, 175,
        178, 183, 193, 178, 173, 174, 183, 183, 180, 170, 178, 182, 180,
        183, 178, 182, 175, 179, 183, 193, 182, 183, 177, 185, 188, 188,
        188, 185, 191,  57,  61],
       [ 57,  57,  58,  57,  57,  61,  54,  68,  51,  49,  64,  50,  48,
         65,  52,  56,  46,  54,  49,  51,  47,  55,  55,  54,  42,  51,
         56,  55,  51,  54,  51,  60,  62,  43,  55,  56,  61,  52,  69,
         64,  46,  54,  47,  70]])

In [52]:
height_and_ages_arr[0,:]

array([189, 170, 189, 163, 183, 171, 185, 168, 173, 183, 173, 173, 175,
       178, 183, 193, 178, 173, 174, 183, 183, 180, 170, 178, 182, 180,
       183, 178, 182, 175, 179, 183, 193, 182, 183, 177, 185, 188, 188,
       188, 185, 191,  57,  61])

In [54]:
height_and_ages_arr[:2, :2]

array([[189, 170],
       [ 57,  57]])

In [56]:
height_and_ages_arr[:,0] = [123,43]

In [57]:
height_and_ages_arr

array([[123, 170, 189, 163, 183, 171, 185, 168, 173, 183, 173, 173, 175,
        178, 183, 193, 178, 173, 174, 183, 183, 180, 170, 178, 182, 180,
        183, 178, 182, 175, 179, 183, 193, 182, 183, 177, 185, 188, 188,
        188, 185, 191,  57,  61],
       [ 43,  57,  58,  57,  57,  61,  54,  68,  51,  49,  64,  50,  48,
         65,  52,  56,  46,  54,  49,  51,  47,  55,  55,  54,  42,  51,
         56,  55,  51,  54,  51,  60,  62,  43,  55,  56,  61,  52,  69,
         64,  46,  54,  47,  70]])

In [58]:
new_record = np.array([[188,190,189,165,180],[58,62,55,68,80]])

In [59]:
new_record

array([[188, 190, 189, 165, 180],
       [ 58,  62,  55,  68,  80]])

In [62]:
new_record.shape

(2, 5)

In [68]:
height_and_ages_arr[:,:5] = new_record

In [73]:
ages_arr = np.array(ages)

In [74]:
ages_arr

array([57, 61, 57, 57, 58, 57, 57, 61, 54, 68, 51, 49, 64, 50, 48, 65, 52,
       56, 46, 54, 49, 51, 47, 55, 55, 54, 42, 51, 56, 55, 51, 54, 51, 60,
       62, 43, 55, 56, 61, 52, 69, 64, 46, 54, 47, 70])

In [76]:
ages_arr.shape

(46,)

In [77]:
ages_arr[:3,]

array([57, 61, 57])

In [82]:
heights_arr = heights_arr.reshape((42,1))
ages_arr = ages_arr.reshape((46,1))

In [83]:
height_age_arr = np.hstack((heights_arr, ages_arr))

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 42 and the array at index 1 has size 46